project:
  type: website

website:
  title: "Hiroki Naganobori"
  navbar:
    left: 
      # - text: "Home"
      #   file: index.qmd
      - text: "Portfolio"
        menu:
          - text: "Overview"
            href: portfolio.qmd
          - text: "Shiny Projects"
            href: portfolio/shiny.qmd
          - text: "Statistical Consulting"
            href: portfolio/consulting.qmd
        # file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Blog"
        file: blog.qmd
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/hnaganob/
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/hnaganob/
        target: _blank
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

